version: '3'
services:
  app:
    image: node:22  # Usando a imagem oficial do Node.js (um único contêiner)
    working_dir: /app
    volumes:
      - ./backend:/app/backend  # Monta o backend no contêiner
      - ./frontend:/app/frontend # Monta o frontend no contêiner
    ports:
      - "3000:3000"  # Porta do backend (Express)
      - "5173:5173"  # Porta do frontend (Vite)
    command: ["bash", "-c", "cd /app/backend && npm install && npm run dev & cd /app/frontend && npm install && npm run dev"]