FROM node:18-alpine

WORKDIR /app

# Copia apenas arquivos de dependências para aproveitar cache
COPY package*.json tsconfig.json ./

# Instala dependências (compila sqlite3 para Linux)
RUN npm install

# Copia o restante do código
COPY . .

EXPOSE 3000

# Inicia em modo dev
CMD ["npm", "run", "dev"]